### ISSUE TITLE
Limited to one label

### ISSUE THREAD

**Issue by 404sooraj** [aakash-a-dev/mAfi#1]
Currently the website only shows "Good First Issues", It would be good if the users gets to choose the tag

**Comment by 404sooraj** [comment]
I would be happy to work on this issue , please assign me.

**Comment by aakash-a-dev** [comment]
Keep the good first issue label as primary as it is for beginners but will love to see what else you can bring on the table.

**Comment by 404sooraj** [comment]
sure
